### ISSUE TITLE
Additional msbuild.exe detection

### ISSUE THREAD

**Issue by rdram0s** [hunters-forge/ThreatHunter-Playbook#14]
I believe there could be an additional item which might be easier (with potentially less noise) for  bypass_whitelisting_msbuild.md.

I am thinking of Sysmon Event ID =3 with Image=msbuild.exe.  My environment contains a significant amount of Event ID =1 since we work in a development environment.

**Comment by Cyb3rWard0g** [comment]
Nice I like that @rdram0s ! We can probably add a section to each playbook to talk about a few use cases. "If X is common in your environment, you could add some more context by adding Y" How does that sound??

**Comment by rdram0s** [comment]
Reviewing this again, is this technique leveraging the msbuild.exe of .NET?  I am trying to determine if I could/should filter the msbuild.exe from the actual location of Visual Studio.  At the same time, I do not want to filter it if an attacker realizes my environment has Visual Studio installed.  Thoughts?

**Comment by bfuzzy** [comment]
@rdram0s I wouldn't filter it out. I would baseline my environment and begin determining outliers. Tying other EventIDs in and looking for suspicious: Image, CommandLine, ParentImage, ParentCommandLine, and CurrentDirectory. Which will filter things down quite a bit.
