### ISSUE TITLE
Link - Results to Page 404

### ISSUE THREAD

**Issue by P0nt05** [hunters-forge/ThreatHunter-Playbook#39]
In the Documentation there is a link for the standardize event fields and combine them with data dictionaries.

Here the original text:
We could easily standardize its event fields and combine them with data dictionaries as shown in here by the OSSEM project.

The Link behind "here" doesn't work anymore:
https://github.com/hunters-forge/OSSEM/blob/master/data_dictionaries/windows/sysmon/event-1.md#data-dictionary

**Comment by P0nt05** [comment]
sorry, here the link to the docu:

https://github.com/hunters-forge/ThreatHunter-Playbook/blob/master/docs/content/pre-hunt/data_standardization.md

**Comment by Cyb3rWard0g** [comment]
Thank you @P0nt05 !
